name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: none
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install composer dependencies
        run: composer upgrade --no-interaction --no-progress --prefer-dist

      - name: Install development dependencies
        run: bash develop/install-development-tools

      - name: Code style
        run: |
          tools/phpcs -sp src/ tests/
          tools/php-cs-fixer fix --dry-run --verbose

      - name: Tests
        run: vendor/bin/phpunit --testdox --verbose

      - name: Code analysis
        run: |
          tools/phpstan analyse --level max --no-progress --verbose src/ tests/
          tools/psalm --no-progress

      - name: infection
        run: phpdbg -qrr tools/infection --no-progress --no-interaction --show-mutations || true
